package com.blog.Dao;

import com.blog.POJO.DO.EssayDO;

import java.util.List;

public interface EssayDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);
    List<EssayDO>  selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    int insert(EssayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    int insertSelective(EssayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    EssayDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    int updateByPrimaryKeySelective(EssayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Sat Mar 30 20:01:42 CST 2019
     */
    int updateByPrimaryKey(EssayDO record);
    int updateById(EssayDO record);
}