package com.blog.Dao;

import com.blog.POJO.DO.EssayDO;
import com.blog.POJO.DO.UserDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    UserDO selectByPrimaryKey(Long id);
    UserDO selectByUsernameAndPassword(@Param(value="username")String username,@Param(value="password")String password);
    UserDO selectByUsernameAndTel(@Param(value="username")String username,@Param(value="tel")String tel);
    UserDO selectByUsername(String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
    int updateById(UserDO record);
}