package com.blog.POJO.VO;

public class UserVO {
    private String username;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    private String nickname;
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sign
     *
     * @mbg.generated Mon Apr 01 16:47:58 CST 2019
     */
    private String sign;
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
